name = "Rascal Modpack"
author = "Rascal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd15a212a65475185e24c697a4fecd6b883d410a58c9258fb1b1eef68ef3a767"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
