name = "Rascal Modpack"
author = "Rascal"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15df6c7dbfbd413e7ba8ee360e8ed1c8a01b6f32cfaaf9998046cc29dc396f3c"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
